### ISSUE TITLE
ProgrammingError at /create/

### ISSUE THREAD

**Issue by Belonias** [codingforentrepreneurs/Advancing-the-Blog#4]
column "read_time" is of type time without time zone but expression is of type integer
LINE 1: ...'', 0, 0, 'awesomeeee', true, '2017-01-01'::date, 1, '2017-0...
                                                             ^
HINT:  You will need to rewrite or cast the expression.
Request Method:	POST
Request URL:	http://pystudygroup.com/create/
Django Version:	1.9
Exception Type:	ProgrammingError
Exception Value:	
column "read_time" is of type time without time zone but expression is of type integer
LINE 1: ...'', 0, 0, 'awesomeeee', true, '2017-01-01'::date, 1, '2017-0...
                                                             ^
HINT:  You will need to rewrite or cast the expression.
Exception Location:	/home/belonias/blog/local/lib/python2.7/site-packages/django/db/backends/utils.py in execute, line 64
Python Executable:	/home/belonias/blog/bin/python
Python Version:	2.7.6
Python Path:	
['/home/belonias/blog/src',
 '/home/belonias/blog/bin',
 '/home/belonias/blog/lib/python2.7',
 '/home/belonias/blog/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/belonias/blog/lib/python2.7/lib-tk',
 '/home/belonias/blog/lib/python2.7/lib-old',
 '/home/belonias/blog/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/belonias/blog/local/lib/python2.7/site-packages']
Server time:	Sun, 19 Feb 2017 18:21:04 +0000

I get this error when I am trying to create a post
I use postgres
I created a new vps, I install everything from  pillow documention and then I follow this guide to deploy https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-14-04
I deleted .pyc files, I did the restarts

**Comment by Aayush567** [comment]
I am also getting the same issue can anyone answer.
